FROM ruby:3.1.4
LABEL maintainer="nabeta@fastmail.fm"

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update -qq && \
  apt-get install -y nodejs postgresql-client imagemagick poppler-utils ffmpeg && npm install -g yarn && yarn install
WORKDIR /enju
ADD Gemfile Gemfile.lock ./
RUN bundle install
ADD package.json yarn.lock ./
RUN yarn install --frozen-lockfile
ADD . /enju/
