production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/enju_leaf_<%= Rails.env %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8981
    log_level: INFO
    path: /solr/enju_leaf_<%= Rails.env %>

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/enju_leaf_<%= Rails.env %>
